handlers:
  queue_listener:
    class: LoggingTools.LoggingHelper.QueueListenerHandler
    handlers:
      - cfg://handlers.console
      - cfg://handlers.file
    queue:
      class: queue.Queue
      maxsize: -1
    respect_handler_level: True