handlers:
  queue_handler:
    class: logging.handlers.QueueHandler
    queue:
      (): queue.Queue
      maxsize: -1
    listener: logging.handlers.QueueListener
    handlers:
      - console
      - file
      