handlers:
  queue_handler:
    class: logging.handlers.QueueHandler
    level: INFO
    queue:
      (): multiprocessing.Queue
      maxsize: -1
    listener: logging.handlers.QueueListener
    handlers:
      - console
      - file
      