version: 1
formatters:
  json:
    class: 'logging.Formatter'
    format: '[%(asctime)s] [%(levelname)s] [%(filename)s:%(lineno)d] - %(message)s'
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  json_file:
    class: logging.FileHandler
    formatter: json
    level: DEBUG
    filename: logs/json_log.log  # Path to the JSON log file
    mode: 'a'  # Append mode
    encoding: 'utf-8'